<?php

namespace AppBundle\Controller;

use Symfony\Bundle\FrameworkBundle\Controller\Controller;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\Routing\Annotation\Route;

use AppBundle\Entity\Categoria;
use AppBundle\Form\CategoriaType;

/**
 * @Route("/gestionCategorias", name="gestionCategorias")
 */
class CategoriaController extends Controller
{
   
    /**
     * @return string
     */
    private function generateUniqueFileName()
    {
        // md5() reduces the similarity of the file names generated by
        // uniqid(), which is based on timestamps
        return md5(uniqid());
    }


    /**
     * @Route("/nuevaCategoria", name="nuevaCategoria")
     */
    public function nuevaCategoriaAction(Request $request)
    {
        $categoria = new Categoria();
        $form = $this->createForm(CategoriaType::class, $categoria);
        
        // Recogemos la inf
        $form->handleRequest($request);
        if ($form->isSubmitted() && $form->isValid()){
            // Rellenar Entity de Categoria
            $categoria = $form->getData();
            // Upload photo
            $fotoFile = $categoria->getFoto();
            // use the original file name
            $fileName = $this->generateUniqueFileName().'.'.$fotoFile->guessExtension();
            // $file->move($directory, $file->getClientOriginalName());
        
            // lugarimg_directory Se define en parameters en config/config
            $fotoFile->move(
                $this->getParameter('lugarimg_directory'),
                $fileName
            );
            $categoria->setFoto($fileName);
            // $categoria->setFechaCreacion(new \DateTime());

            // Almacenar nuevo lugar
            // $entityManager = $em
            $em = $this->getDoctrine()->getManager();
            // Objeto que queremos almacenar
            $em->persist($categoria);
            // Finalizar comunicación con bd
            $em->flush();

            return $this->redirectToRoute('categoria', ['id' => $categoria->getId()]);
        }
        return $this->render('gestionCategoria/nuevoCategoria.html.twig', [
            'form' => $form->createView(),
        ]);
    }

}
